controllers/SiteController.php
<?php

namespace app\controllers;

use Yii;
use app\models\Patients;
use app\models\Genres;
use app\models\Wilayas;
use app\models\Visites;
use app\models\PatientsSearch;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;
use yii\helpers\ArrayHelper;
use yii\web\Response;
use kartik\mpdf\Pdf;


/**
 * SiteController implements the CRUD actions for Patients model.
 */
class SiteController extends Controller
{
    /**
     * @inheritdoc
     */
    public function init()
    {
      \Yii::$app->language = 'fr_FR';
      Parent::init();
    }
    public function behaviors()
    {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['POST'],
                ],
            ],
        ];
    }

    /**
     * Lists all Patients models.
     * @return mixed
     */
    public function actionIndex()
    {
        $searchModel = new PatientsSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams,['wilaya']);
        //dd($dataProvider->getModels());
        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }
    public function actionIndexAjax()
    {
      $searchModel = new PatientsSearch();
      $dataProvider = $searchModel->search(Yii::$app->request->queryParams,['wilaya']);
      //dd($dataProvider->getModels());
      return $this->renderAjax('index', [
          'searchModel' => $searchModel,
          'dataProvider' => $dataProvider,
      ]);
    }



    public function actionDatatables()
    {
        return [
             'datatables' => [
                 'class' => 'nullref\datatable\DataTableAction',
                 'query' => Patients::find()->with('wilaya'),
                 'applyOrder' => function($query, $columns, $order) {
                    //custom ordering logic
                    return $query;
                 },
                 'applyFilter' => function($query, $columns, $search) {
                    //custom search logic
                    return $query;
                 },
             ],
        ];
    }
    /**
     * Displays a single Patients model.
     * @param integer $id
     * @return mixed
     */
    public function actionView($id)
    {
        $visites= Visites::find()->where(['patient_id' => $id])->orderBy('id DESC')->all();
        $model=$this->findModel($id);

        $age= date_diff(date_create($model->naissance), date_create('today'))->y;

        return $this->render('view', [
            'model' => $model,
            'visites'=> $visites,
            'age'=>$age,
        ]);
    }
    public function actionViewAjax($id)
    {
        $visites= Visites::find()->where(['patient_id' => $id])->orderBy('id DESC')->all();
        $model=$this->findModel($id);
        $age= date_diff(date_create($model->naissance), date_create('today'))->y;

        return $this->renderAjax('view', [
            'model' => $model,
            'visites'=> $visites,
            'age'=>$age,
        ]);
    }

    public function actionOrdonnance($id) {

    $visite= Visites::find()->with('patient')->where(['id'=>$id])->one();
    //dd($visite);
    //$traitement=  Yii::$app->request->post('traitement');
    // get your HTML raw content without any layouts or scripts
    $content = $this->renderPartial('_ordonnance',['visite'=>$visite]);

    // setup kartik\mpdf\Pdf component
    $pdf = new Pdf([
        // set to use core fonts only
        'mode' => Pdf::MODE_UTF8,
        // A4 paper format
        'format' => [148,210],//Pdf::FORMAT_LEGAL,
        // portrait orientation
        'orientation' => Pdf::ORIENT_PORTRAIT,
        // stream to browser inline
        'destination' => Pdf::DEST_BROWSER,
        // your html content input
        'content' => $content,
        // format content from your own css file if needed or use the
        // enhanced bootstrap css built by Krajee for mPDF formatting
        'cssFile' => '@vendor/bower/bootstrap/dist/css/bootstrap.min.css',
        // any css to be embedded if required
        'cssInline' => '.mrg{margin-right:50px;} div{font-size:15px; display:inline-block; } .bld{font-weight:bold}',
         // set mPDF properties on the fly
        'options' => ['title' => 'ordonnancelogiciel swiftmed'],
         // call mPDF methods on the fly
        'methods' => [
            'SetFooter'=>['générée par le logiciel swiftmed '],
            //'SetFooter'=>['{PAGENO}'],
        ]
    ]);

        // return the pdf output as per the destination setting
        return $pdf->render();
    }

    protected function frdatetosql($date)
    {
      //convert frenhc date to date
     $find = array('janvier', 'février', 'mars', 'avril', 'mai', 'juin', 'juillet', 'août', 'septembre', 'octobre', 'novembre', 'décembre');
     $replace = array('January', 'February', 'March', 'April', 'May', 'June', 'July', 'August', 'September', 'October', 'November', 'December');
     $date = str_replace($find, $replace, strtolower($date));
     $date = date('Y/m/d', strtotime($date));

     return $date;
    }
    public function actionNextVisit()
    {
      if(Yii::$app->request->isAjax)
      {
        $post=Yii::$app->request->Post();
        $patient=Patients::findOne($post['id']);



        //var_dump(date_parse($arr));
        //var_dump(date_parse());

        $patient->next_visit=$this->frdatetosql($post['date']);
        if($patient->save())
        {
          return 'true';
        }else return 'false';
      }
    }
    /**
     * Creates a new Patients model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
        $model = new Patients();

        $genders = ArrayHelper::map(Genres::find()->all(), 'id', 'nom');
        $Wilayas = ArrayHelper::map(Wilayas::find()->all(), 'code', 'nom');
        $post=Yii::$app->request->post();
        //var_dump($post);die();
        //dd($post);
        if($post)$post['Patients']['naissance']=$this->frdatetosql($post['Patients']['naissance']);
        if ($model->load($post) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->id]);
            //return $this->runAction('view-ajax',['id' => $model->id]);
        } else {
            return $this->render('create', [
                'model' => $model,
                'genres' => $genders,
                'wilayas' => $Wilayas
            ]);
        }
    }
    public function actionCreateAjax()
    {
        $model = new Patients();

        $genders = ArrayHelper::map(Genres::find()->all(), 'id', 'nom');
        $Wilayas = ArrayHelper::map(Wilayas::find()->all(), 'code', 'nom');
        $post=Yii::$app->request->post();
        //var_dump($post);die();
        //dd($post);


        if($post)$post['Patients']['naissance']=$this->frdatetosql($post['Patients']['naissance']);
        if ($model->load($post) && $model->save()) {
            //return $this->renderAjax('view', ['id' => $model->id]);
            return $this->runAction('view-ajax',['id' => $model->id]);

        } else {
            return $this->renderAjax('create', [
                'model' => $model,
                'genres' => $genders,
                'wilayas' => $Wilayas
            ]);
        }
    }

    /**
     * Updates an existing Patients model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     */
    public function actionUpdate($id)
    {
        $model = $this->findModel($id);
        $genders = ArrayHelper::map(Genres::find()->all(), 'id', 'nom');
        $Wilayas = ArrayHelper::map(Wilayas::find()->all(), 'code', 'nom');
        $post=Yii::$app->request->post();
        if($post)$post['Patients']['naissance']=$this->frdatetosql($post['Patients']['naissance']);

        if ($model->load($post) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->id]);
        } else {
            return $this->render('update', [
                'model' => $model,
                'genres' => $genders,
                'wilayas' => $Wilayas
            ]);
        }
    }
    public function actionUpdateAjax($id)
    {
        $model = $this->findModel($id);
        $genders = ArrayHelper::map(Genres::find()->all(), 'id', 'nom');
        $Wilayas = ArrayHelper::map(Wilayas::find()->all(), 'code', 'nom');
        $post=Yii::$app->request->post();
        if($post)$post['Patients']['naissance']=$this->frdatetosql($post['Patients']['naissance']);

        if ($model->load($post) && $model->save()) {
          return $this->runAction('view-ajax',['id' => $model->id]);
        } else {
            return $this->renderAjax('update', [
                'model' => $model,
                'genres' => $genders,
                'wilayas' => $Wilayas
            ]);
        }
    }

    /**
     * Deletes an existing Patients model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     */
    public function actionDelete($id)
    {
        $this->findModel($id)->delete();

        return $this->redirect(['index']);
    }

    /**
     * Finds the Patients model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return Patients the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = Patients::findOne($id)) !== null) {
            return $model;
        } else {
            throw new NotFoundHttpException('The requested page does not exist.');
        }
    }
}

views/layouts/main.php
<?php

/* @var $this \yii\web\View */
/* @var $content string */

use yii\helpers\Html;
use yii\bootstrap\Nav;
use yii\bootstrap\NavBar;
use yii\widgets\Breadcrumbs;
use app\assets\AppAsset;
use yii\widgets\Pjax;

AppAsset::register($this);
\conquer\momentjs\MomentjsAsset::register($this);
?>
<?php $this->beginPage() ?>
<!DOCTYPE html>
<html lang="<?= Yii::$app->language ?>">
<head>
    <meta charset="<?= Yii::$app->charset ?>">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <?= Html::csrfMetaTags() ?>
    <title><?= Html::encode($this->title) ?></title>
    <?php $this->head() ?>
</head>
<body>
<?php $this->beginBody() ?>

<div class="wrap">

    <?php
    NavBar::begin([
        'brandLabel' => '<img src="images/logo.png" class="img-responsive col-md-4"/>',
        'brandUrl' => Yii::$app->homeUrl,
        'options' => [
            'class' => 'navbar-inverse navbar-fixed-top',
        ],
    ]);
    echo Nav::widget([
        'options' => ['class' => 'navbar-nav navbar-right'],
        'items' => [
            ['label' => 'Liste des Patients','linkOptions'=>['class'=>'ajax-request'], 'url' => ['/site/index-ajax']],
            ['label' => 'Nouveau Patient','linkOptions'=>['class'=>'ajax-request'], 'url' => ['/site/create-ajax']],
            //['label' => 'Visites', 'url' => ['/site/about']],


        ],
    ]);
    NavBar::end();
    ?>
    <div class="container">
        <?php /* Breadcrumbs::widget([
            'links' => isset($this->params['breadcrumbs']) ? $this->params['breadcrumbs'] : [],
        ]) */?>
        <?= $content ?>
    </div>
    <div id="loading" class="collapse"><div><img src="images/loading.svg"/></div></div>

</div>

<footer class="footer">
    <div class="container">
        <p class="pull-left"><a href="http://www.optidev-dz.com">&copy; optidev</a> <?= date('Y') ?></p>

     </div>
</footer>
<?php $this->endBody() ?>
</body>

<script>
  $(document).ready(function() {
$(document).on('click','#historique .visite', function(event) {
  //console.log($(event.target).data('value'));
  $('.visite_heading').text('Date de la visite:');
  $('.selected').toggleClass('selected');
  $(event.target).toggleClass('selected');
  val= $(event.target).data('value');

  if($('#new-visit-container').length)
  $('#new-visit-container').fadeOut(500,function(){
    $('#visit-container').fadeIn(500);

  });
  //else $('#new-visit-container').fadeIn(500);

  moment.locale('fr');

  $.post('/visites/visit', {id: val}, function(data, textStatus, xhr) {
    date=moment(data.date_visite).format("Do MMM YYYY");

    $('#date-visite').fadeOut(500, function() {
        $(this).text(date).fadeIn(500);


    });

    $('#print-link').fadeOut(500, function() {
        $(this).attr('href',"ordonnance?id="+val).fadeIn(500);
    });

    $('#motif_record').fadeOut(500, function() {
        $(this).text('');
        $(this).text(data.motif).fadeIn(500);
    });
    $('#interrogatoire_record').fadeOut(500, function() {
        $(this).text('');
        $(this).text(data.interogatoire).fadeIn(500);
    });
    $('#exam_cli_record').fadeOut(500, function() {
        $(this).text('');
        $(this).text(data.examen_clinique).fadeIn(500);
    });
    $('#exam_bio_record').fadeOut(500, function() {
        $(this).text('');
        $(this).text(data.examen_biologique).fadeIn(500);
    });
    $('#exam_radio_record').fadeOut(500, function() {
        $(this).text('');
        $(this).text(data.examen_radiologique).fadeIn(500);
    });
    $('#exploration_record').fadeOut(500, function() {
        $(this).text('');
        $(this).text(data.exploration_fonctionnelle).fadeIn(500);
    });

    $('#prevention_record').fadeOut(500, function() {
        $(this).text('');
        $(this).text(data.prevention).fadeIn(500);
    });

    $('#diagnostic_record').fadeOut(500, function() {
        $(this).text('');
        $(this).text(data.diagnostic).fadeIn(500);
    });
    $('#prescription_record').fadeOut(500, function() {
        $(this).text('');
        $(this).text(data.prescription).fadeIn(500);
    });

  });
});

$(document).on('click','#new-visit', function(event) {

  moment.locale('fr');
  date=moment().format("Do MMM YYYY");

  if($('#visit-container').length)
  $('#visit-container').fadeOut(500,function(){
    $('#new-visit-container').fadeIn(500);

  });
  else $('#new-visit-container').fadeIn(500);



  $('#date-visite').fadeOut(500, function() {
      $(this).text(date).fadeIn(500);
  });
  // $('#diagnostic').fadeOut(500, function() {
  //     $(this).html('<textarea class="col-md-12"></textarea>').fadeIn(500);
  // });
  // $('#prescription').fadeOut(500, function() {
  //     $(this).html('<textarea class="col-md-12"></textarea>').fadeIn(500);
  // });
  $('#save-visit').fadeIn(500);
});


$(document).on('click','#save-visit', function(event) {
  event.preventDefault();

   answer=confirm("êtes-vous sûr de vouloir clôturer la visite ?");


  if(!answer) return false;
  id=$('#id-patient').text();
  date=$('#date-visite').text();
  //diag=$('#diagnostic').children('textarea')[0].value;
  //pres=$('#prescription').children('textarea')[0].value;
  form= $('#new-visit-container').serializeArray()
  //console.log(form);
  $.post('/visites/save-visit', {id:id, date: date, form:form }, function(data, textStatus, xhr) {

    $('#new-visit-container').fadeOut(500,function(){
      $('#visit-container').fadeIn(500);
      $('#new-visit-container textarea').each(function(index, el) {
        el.value='';
        //console.log(el.value);
      });
    });

    $('#date-visite').fadeOut(500, function() {
        $(this).text(date).fadeIn(500);
    });

    $('#motif_record').fadeOut(500, function() {
        $(this).text(form[0].value).fadeIn(500);
    });
    $('#interrogatoire_record').fadeOut(500, function() {
        $(this).text(form[1].value).fadeIn(500);
    });
    $('#exam_cli_record').fadeOut(500, function() {
        $(this).text(form[2].value).fadeIn(500);
    });
    $('#exam_bio_record').fadeOut(500, function() {
        $(this).text(form[3].value).fadeIn(500);
    });
    $('#exam_radio_record').fadeOut(500, function() {
        $(this).text(form[4].value).fadeIn(500);
    });
    $('#exploration_record').fadeOut(500, function() {
        $(this).text(form[5].value).fadeIn(500);
    });
    $('#diagnostic_record').fadeOut(500, function() {
        $(this).text(form[6].value).fadeIn(500);
    });
    $('#prevention_record').fadeOut(500, function() {
        $(this).text(form[7].value).fadeIn(500);
    });
    $('#prescription_record').fadeOut(500, function() {
        $(this).text(form[8].value).fadeIn(500);
    });


    newval= ($('.visite').length)?parseInt($('.visite')[0].dataset.value,10)+1:0;
    //console.log(newval);
    $('.selected').toggleClass('selected');
    $("#historique>ul").prepend('<li class="visite selected" data-value="'+newval+'">'+date+'</li>');
    $('.selected').fadeOut(400,function(){
        $('.selected').fadeIn(400);
    });
    $('#print-link').fadeOut(500, function() {
        $(this).attr('href',"ordonnance?id="+newval).fadeIn(500);
    });

  });
});








    $('#welcome').fadeIn('fast', function() {
      $('#welcome h1').fadeIn(1000,function(){

          $(this).animate({
                  'margin-top': '50px'
                }, 'medium', function() {
                  // Animation complete.
                  $('#welcome h2').fadeIn(400, function(){
                    setTimeout(function() {
                      $('#welcome').fadeOut();
                    }, 1000);
                  });
              });
      });
    });

    $(document).on('change','#next-visit', function(event) {
      val=event.target.value
      console.log(val);
      id=$('#id-patient').text();
      console.log(id);

      $.post('/next-visit', {id:id,date: val}, function(data, textStatus, xhr) {
        if(data=='true') $('#saved').fadeOut('500', function() {
          $(this).text('Date enregistrée.').fadeIn(500, function() {

          }).delay(3000).fadeOut('500');
        });
      });


  });

    $(".dataTable.no-footer").attr({style: '' });
    $(".patients-index").fadeIn(400);
    $(".patients-form").fadeIn(400);
    $(".patients-view").fadeIn(400);

    $(document).on('click','.ajax-request', function(event) {
      event.preventDefault();

      $.post($(event.target).attr('href'), function(data, textStatus, xhr) {

        $('.wrap > .container').html(data);

        //$(".patients-create").fadeIn(400);

      });

    });

    $(document).on('click','.ajax-request-form', function(event) {
      event.preventDefault();
      post=$('.patients-form form').serializeArray();
      //console.log(post);
      $.post($(event.target).attr('href'), post, function(data, textStatus, xhr) {

        $('.wrap > .container').html(data);

        //$(".patients-create").fadeIn(400);

      });

    });

    $( document ).ajaxStart(function() {
      $( "#loading" ).fadeIn();
    });

    $( document ).ajaxStop(function() {
      $( "#loading" ).fadeOut();
    });

  });

  $(document).ajaxComplete(function(event) {
    //console.log(event.target);
    $(".dataTable.no-footer").attr({style: '' });
    $(".patients-index").fadeIn(400);
    $(".patients-form").fadeIn(400);
    $(".patients-view").fadeIn(400);
/*
    $(document).on('click','.ajax-request', function(event) {
      event.preventDefault();

      $.post($(event.target).attr('href'), function(data, textStatus, xhr) {

        $('.wrap > .container').html(data);

        //$(".patients-create").fadeIn(400);

      });

    });
    $(document).on('click','.ajax-request-form', function(event) {
      event.preventDefault();
      post=$('.patients-form form').serializeArray();
      //console.log(post);
      $.post($(event.target).attr('href'), post, function(data, textStatus, xhr) {

        $('.wrap > .container').html(data);

        //$(".patients-create").fadeIn(400);

      });

    });

/*
    $( document ).ajaxStart(function() {
      $( "#loading" ).show();
    });
    $( document ).ajaxStop(function() {
      $( "#loading" ).hide();
    });*/
  });

</script>
</html>
<?php $this->endPage() ?>